### ISSUE TITLE
Changing # sign to an image

### ISSUE THREAD

**Issue by nehemie-n** [jbw91/angular-emojione#6]
Thanks for your awesome job.
In the app that I am developing I am trying to use the pipe to transform the text to be of emojione images, but I am stuck at the #sign.
When I try to convert the text, it also converts #signs before the hashtag into images. If there is something you can help me, I can appreciate that because I want the hashtag to stay as a hashtag without emoji.

**Comment by johnbwoodruff** [comment]
Thanks for reporting! I'll do some tests and see if I can reproduce this issue.

**Comment by johnbwoodruff** [comment]
This appears to be an issue reported to the emojione project: emojione/emojione#599 

As I simply pass text through to the emojione service, I would guess this issue is on their end. A comment suggested downgrading the emojione version to 3.1.4 which doesn't have the issue. Closing as an issue with the emojione library itself.
